### ISSUE TITLE
missing dependencies during installation

### ISSUE THREAD

**Issue by aozalevsky** [artyomovlab/dualsimplex#25]
I'm not a proficient R user, so please forgive for the naive comments. 

I was following installation guide from the readme page and got following error message:
`ERROR: dependency ‘Biobase’ is not available for package ‘DualSimplex’`

I guessed that it was a Bioconductor package and indeed, after it's installation i was able to get `DualSimplex` up and running.

**Comment by denklewer** [comment]
Thank you, we will fix it. Feel free to report any other missing dependency

**Comment by denklewer** [comment]
Fixed , should work now
