### ISSUE TITLE
Sinkhorn convergence check

### ISSUE THREAD

**Issue by scjlee** [artyomovlab/dualsimplex#37]
The current implementation does not make sure Sinkhorn transformation is converged. In theory, the convergence could be tested by testing whether column sums of V_row all equal to N/M.

I implement such test in RcppArmadillo, which won't cost too much computational burden. Though it does not follow the current API. I will make a pull request when I fix it.

![Screenshot from 2024-12-14 07-30-22](https://github.com/user-attachments/assets/56182139-9a89-4985-bfa9-f7361a786b2a)

**Comment by denklewer** [comment]
fixed in #41
